logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
    application:
        name: introduction-to-ai
    main:
        banner-mode: "off"
        log-startup-info: false
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            chat:
                options:
                    model: gpt-4o-mini
                    